[versions]

junit = "5.9.2"

kotlin = "1.9.0"

[libraries]

assertj = { module = "org.assertj:assertj-core", version = "3.19.0" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

pluginz-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
dependencyanalysis = "com.autonomousapps.dependency-analysis:1.20.0"
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
license = "com.jaredsburrows.license:0.9.3"
kotlinx-binary-compatibility-validator = "org.jetbrains.kotlinx.binary-compatibility-validator:0.13.2"