[versions]

junit = "5.10.0"

kotlin = "1.9.10"

[libraries]

assertj = { module = "org.assertj:assertj-core", version = "3.24.2" }

jetbrains-annotations = { module = "org.jetbrains:annotations", version = "24.0.1" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

mockito = { module = "org.mockito:mockito-core", version = "5.6.0" }

pluginz-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
dependencyanalysis = "com.autonomousapps.dependency-analysis:1.24.0"
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
license = "com.jaredsburrows.license:0.9.3"
nexus-publish = "io.github.gradle-nexus.publish-plugin:1.3.0"
kotlinx-binary-compatibility-validator = "org.jetbrains.kotlinx.binary-compatibility-validator:0.13.2"
